language: go
go:
 - 1.8

services:
  - docker  

before_install:
 - go get github.com/sirupsen/logrus 
 - go get github.com/AVENTER-UG/util
 - go get github.com/mattn/go-sqlite3
 - go get github.com/prometheus/client_golang/prometheus
 - go get github.com/matrix-org/dugong
 - go get github.com/AVENTER-UG/gomatrix
 - go get github.com/mattn/go-shellwords
 - go get gopkg.in/yaml.v2
 - go get golang.org/x/oauth2
 - go get github.com/google/go-github/github
 - go get gopkg.in/alecthomas/kingpin.v2
 - go get github.com/russross/blackfriday
 - go get github.com/aws/aws-sdk-go
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo
 - go get github.com/client9/misspell/...
 - go get github.com/gordonklaus/ineffassign
 - go get github.com/optiopay/klar

install:
  - go build init.go app.go
  - docker run -d --name db arminc/clair-db:$(date -d "1 day ago" +%Y-%m-%d)
  - docker run -d -p 6060-6061:6060-6061 --link db:postgres --name clair arminc/clair-local-scan:v2.0.1     
  

script: 
  - ./hooks/pre-commit
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t avhost/go-avbot:clair .  
  - docker push avhost/go-avbot:clair
  - CLAIR_ADDR=http://localhost CLAIR_OUTPUT=High CLAIR_THRESHOLD=10 klar avhost/go-avbot:clair

after_success:  
  - docker build -t avhost/go-avbot:$TRAVIS_BRANCH .
  - docker push avhost/go-avbot:$TRAVIS_BRANCH
  - "curl --user $MARATHON_WEBHOOK_USERNAME:$MARATHON_WEBHOOK_PASSWORD -k -XPOST -H 'Content-Type: application/json' https://$MARATHON_WEBHOOK_URL/v2/apps$MARATHON_WEBHOOK_ID/restart"

notifications:
  webhooks: $AVBOT_WEBHOOK  