language: go
go:
 - 1.8

services:
  - docker

before_install:
 - go get github.com/sirupsen/logrus 
 - go get github.com/AVENTER-UG/util
 - go get github.com/mattn/go-sqlite3
 - go get github.com/prometheus/client_golang/prometheus
 - go get github.com/matrix-org/dugong
 - go get github.com/AVENTER-UG/gomatrix
 - go get github.com/mattn/go-shellwords
 - go get gopkg.in/yaml.v2
 - go get golang.org/x/oauth2
 - go get github.com/google/go-github/github
 - go get gopkg.in/alecthomas/kingpin.v2
 - go get github.com/russross/blackfriday
 - go get github.com/aws/aws-sdk-go
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo
 - go get github.com/client9/misspell/...
 - go get github.com/gordonklaus/ineffassign

install:
  - go build init.go app.go

script: ./hooks/pre-commit

after_success:
  - docker build -t avhost/go-avbot:$TRAVIS_BRANCH .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push avhost/go-avbot:$TRAVIS_BRANCH
  - "curl --user $MARATHON_WEBHOOK_USERNAME:$MARATHON_WEBHOOK_PASSWORD -k -XPOST -H 'Content-Type: application/json' https://$MARATHON_WEBHOOK_URL/v2/apps$MARATHON_WEBHOOK_ID/restart"

notifications:
  webhooks: $AVBOT_WEBHOOK
  
