language: go
go:
 - 1.8
install:
 - go get github.com/sirupsen/logrus 
 - go get github.com/matrix-org/util
 - go get github.com/mattn/go-sqlite3
 - go get github.com/prometheus/client_golang/prometheus
 - go get github.com/matrix-org/dugong
 - go get github.com/AVENTER-UG/gomatrix
 - go get github.com/mattn/go-shellwords
 - go get gopkg.in/yaml.v2
 - go get golang.org/x/oauth2
 - go get github.com/google/go-github/github
 - go get gopkg.in/alecthomas/kingpin.v2
 - go get github.com/russross/blackfriday
 - go get github.com/aws/aws-sdk-go
 - go get github.com/golang/lint/golint
 - go get github.com/fzipp/gocyclo
 - go get github.com/client9/misspell/...
 - go get github.com/gordonklaus/ineffassign

script: ./hooks/pre-commit

after_success:
  - curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "v0.0.3"}' -X POST https://registry.hub.docker.com/u/avhost/docker-go-avbot/trigger/b7b4850f-96c7-435e-b077-f4de515d1e26/
  - curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://registry.hub.docker.com/u/avhost/docker-go-avbot/trigger/b7b4850f-96c7-435e-b077-f4de515d1e26/  

